import { Document, Page, Text, View } from '@react-pdf/renderer';
import { PaymentReceipt } from '../../types';
import { Letterhead } from './Letterhead';
import { commonStyles } from './shared';

interface Props {
  receipt: PaymentReceipt;
}

export function ReceiptPDF({ receipt }: Props) {
  const { snapshot } = receipt;

  return (
    <Document>
      <Page size="A4" style={commonStyles.page}>
        <Letterhead settings={snapshot.companySettings} />
        
        <View style={{ flexDirection: 'row', justifyContent: 'space-between', marginBottom: 5 }}>
          <Text style={{ fontSize: 10 }}>Receipt No: {receipt.receiptNumber}</Text>
          <Text style={{ fontSize: 10 }}>Date: {new Date(snapshot.date).toLocaleDateString()}</Text>
        </View>
        
        <Text style={commonStyles.title}>Payment Receipt</Text>
        
        <View style={{ marginBottom: 20, gap: 10 }}>
          <Text style={{ fontSize: 11, lineHeight: 1.5 }}>
            Received with thanks from <Text style={{ fontWeight: 'bold' }}>{snapshot.clientName}</Text> 
            {' '}the sum of <Text style={{ fontWeight: 'bold' }}>Rs. {snapshot.amountReceived.toLocaleString()}/-</Text>
          </Text>
          <Text style={{ fontSize: 11, lineHeight: 1.5 }}>
            Towards project: <Text style={{ fontWeight: 'bold' }}>{snapshot.projectName}</Text>
          </Text>
          <Text style={{ fontSize: 11, lineHeight: 1.5 }}>
            Payment Mode: <Text style={{ fontWeight: 'bold' }}>{snapshot.paymentMode.toUpperCase()}</Text>
          </Text>
          <Text style={{ fontSize: 11, lineHeight: 1.5 }}>
            Remaining Balance: <Text style={{ fontWeight: 'bold' }}>Rs. {snapshot.remainingBalance.toLocaleString()}/-</Text>
          </Text>
        </View>
        
        <View style={{ marginTop: 50, flexDirection: 'row', justifyContent: 'flex-end' }}>
          <View style={{ alignItems: 'center' }}>
            <Text style={{ fontSize: 10, marginBottom: 40 }}>For {snapshot.companySettings.name}</Text>
            <Text style={{ fontSize: 10, borderTopWidth: 1, paddingTop: 5, width: 150, textAlign: 'center' }}>
              Authorized Signatory
            </Text>
          </View>
        </View>
        
        <Text style={commonStyles.footer}>Generated by Deepthi Construction CRM</Text>
      </Page>
    </Document>
  );
}
