import { Document, Page, Text, View, Image } from '@react-pdf/renderer';
import { QuotationVersion } from '../../types';
import { Letterhead } from './Letterhead';
import { commonStyles } from './shared';

interface Props {
  quotation: QuotationVersion;
}

export function TypeALabourPDF({ quotation }: Props) {
  const isTa = quotation.language === 'ta';
  const t = quotation.tamilTranslations || {};
  const fontFamily = isTa ? 'NotoSansTamil' : undefined;

  return (
    <Document>
      <Page size="A4" style={{ ...commonStyles.page, fontFamily }}>
        <Letterhead settings={quotation.companySnapshot} />
        
        <View style={{ flexDirection: 'row', justifyContent: 'space-between', marginBottom: 5 }}>
          <Text style={{ fontSize: 10 }}>Location of the Project: {quotation.siteName}</Text>
          <Text style={{ fontSize: 10 }}>Date: {new Date(quotation.date).toLocaleDateString()}</Text>
        </View>
        <View style={{ marginBottom: 15 }}>
          <Text style={{ fontSize: 10 }}>Name Of the Client: {quotation.clientName}</Text>
        </View>
        
        <Text style={{ ...commonStyles.title, fontFamily }}>{isTa && t.subject ? t.subject : 'Labour Quotation'}</Text>
        <Text style={{ textAlign: 'center', fontSize: 12, fontWeight: 'bold', marginBottom: 10, fontFamily }}>Statement of Specification</Text>
        
        {/* Labour Cost Box */}
        <View style={{ backgroundColor: '#d1d5db', padding: 8, marginBottom: 15 }}>
          <Text style={{ textAlign: 'center', fontWeight: 'bold', marginBottom: 4, fontFamily }}>Labour Cost:</Text>
          <View style={{ flexDirection: 'row', justifyContent: 'center', gap: 20 }}>
            {quotation.labourItems?.map((item, idx) => (
              <Text key={idx} style={{ fontWeight: 'bold', fontFamily }}>{item.floor} Rs. {item.ratePerSqft}/-</Text>
            ))}
          </View>
        </View>
        
        {/* Scope of Work */}
        <View style={{ marginBottom: 20, paddingLeft: 20 }}>
          {quotation.labourScope?.map((item, idx) => {
            const desc = isTa && t.labourScope?.[item.id] ? t.labourScope[item.id] : item.description;
            return (
              <Text key={item.id} style={{ marginBottom: 5, fontSize: 10, lineHeight: 1.4, fontFamily }}>
                {idx + 1}. {desc}{item.measurement ? ` : ${item.measurement}` : ''}
              </Text>
            );
          })}
        </View>
        
        {/* Notes */}
        {quotation.notes && (
          <View style={{ marginTop: 20 }}>
            <Text style={{ fontWeight: 'bold', textDecoration: 'underline', marginBottom: 5, fontFamily }}>Notes: Additional works</Text>
            <Text style={{ fontSize: 10, lineHeight: 1.5, paddingLeft: 10, fontFamily }}>{isTa && t.notes ? t.notes : quotation.notes}</Text>
          </View>
        )}
        <View style={{ marginTop: 20, paddingTop: 20, flexDirection: 'row', justifyContent: 'space-between' }}>
          <View style={{ alignItems: 'center', justifyContent: 'flex-end' }}>
            <Text style={{ fontSize: 10, marginBottom: 40, fontFamily }}>Accepted By (Client)</Text>
            <Text style={{ fontSize: 10, fontWeight: 'bold', fontFamily }}>{quotation.clientName}</Text>
          </View>
          <View style={{ alignItems: 'center', justifyContent: 'flex-end' }}>
            <Text style={{ fontSize: 10, marginBottom: quotation.showOwnerSignature && quotation.companySnapshot.signatureUrl ? 5 : 40, fontFamily }}>For {quotation.companySnapshot.name}</Text>
            {quotation.showOwnerSignature && quotation.companySnapshot.signatureUrl && (
              <Image src={quotation.companySnapshot.signatureUrl} style={{ width: 100, height: 40, objectFit: 'contain', marginBottom: 5 }} />
            )}
            <Text style={{ fontSize: 10, fontWeight: 'bold', fontFamily }}>Authorized Signatory</Text>
          </View>
        </View>
        
        <Text style={commonStyles.footer}>Generated by Deepthi Construction CRM - Quotation #{quotation.quotationNumber}</Text>
      </Page>
    </Document>
  );
}
