/**
 * Schedule activities for the demo projects.
 *
 * Invented, like everything else in the demo. The point of this file is that
 * the Schedule tab has to look like a real construction programme the moment
 * it opens - a builder can tell a plausible sequence from a made-up one in
 * about three seconds, and an empty or nonsense Gantt kills the pitch.
 *
 * So the sequences below are the actual order these jobs happen in: you cannot
 * plaster before blockwork, conduiting runs alongside blockwork rather than
 * after it, and the slab has to cure before columns go up on top of it.
 *
 * Baselines are generated by running the CPM engine twice - once on the clean
 * plan, which is saved as the baseline, and again with the real-world delays
 * applied. That means the variance figures on screen are genuinely calculated
 * rather than typed in, and they stay consistent if anyone edits a duration
 * mid-demo.
 */

import { store } from './store';
import { OWNER_UID } from './auth';
import { ScheduleActivity, DependencyType } from '../types';
import { computeSchedule, workingDaysBetween } from '../lib/cpm';

interface TemplateRow {
  /** Stable key, used to wire predecessors within a template. */
  key: string;
  name: string;
  /** Which of the five stages this belongs under (1-based). */
  stage: number;
  days: number;
  /** Predecessor keys. A bare string is a normal Finish-to-Start link. */
  after?: (string | { key: string; type: DependencyType; lag?: number })[];
  /** Dropped for single-storey jobs like the godown. */
  upperFloor?: boolean;
  budget?: number;
}

/** Ground + 1 residential / commercial build. */
const BUILD_TEMPLATE: TemplateRow[] = [
  { key: 'layout', name: 'Site clearing & layout marking', stage: 1, days: 3, budget: 18000 },
  { key: 'excav', name: 'Excavation for footings', stage: 1, days: 6, after: ['layout'], budget: 62000 },
  { key: 'pcc', name: 'PCC bed', stage: 1, days: 2, after: ['excav'], budget: 34000 },
  { key: 'footrebar', name: 'Footing reinforcement', stage: 1, days: 4, after: ['pcc'], budget: 128000 },
  { key: 'footpour', name: 'Footing concrete pour', stage: 1, days: 2, after: ['footrebar'], budget: 96000 },
  { key: 'plinth', name: 'Plinth beam & backfilling', stage: 1, days: 6, after: ['footpour'], budget: 142000 },

  { key: 'gfcol', name: 'Ground floor columns', stage: 2, days: 5, after: ['plinth'], budget: 156000 },
  { key: 'gfshutter', name: 'Ground floor slab shuttering', stage: 2, days: 6, after: ['gfcol'], budget: 88000 },
  { key: 'gfrebar', name: 'Ground floor slab reinforcement', stage: 2, days: 4, after: ['gfshutter'], budget: 172000 },
  { key: 'gfpour', name: 'Ground floor slab pour', stage: 2, days: 2, after: ['gfrebar'], budget: 118000 },
  { key: 'gfcure', name: 'Slab curing', stage: 2, days: 10, after: ['gfpour'], budget: 9000 },
  { key: 'ffcol', name: 'First floor columns', stage: 2, days: 6, after: ['gfcure'], upperFloor: true, budget: 134000 },
  { key: 'ffslab', name: 'First floor slab', stage: 2, days: 8, after: ['ffcol'], upperFloor: true, budget: 246000 },

  // Blockwork starts a few days into curing rather than waiting it out - this
  // is the sort of overlap a scheduler looks for, so the demo should show one.
  { key: 'gfblock', name: 'Blockwork — ground floor', stage: 3, days: 10, after: [{ key: 'gfcure', type: 'SS', lag: 4 }], budget: 214000 },
  { key: 'ffblock', name: 'Blockwork — first floor', stage: 3, days: 10, after: ['ffslab', 'gfblock'], upperFloor: true, budget: 198000 },
  { key: 'lintel', name: 'Lintels & sunshades', stage: 3, days: 4, after: ['gfblock'], budget: 76000 },
  { key: 'extplaster', name: 'External plastering', stage: 3, days: 12, after: ['lintel'], budget: 168000 },
  { key: 'intplaster', name: 'Internal plastering', stage: 3, days: 12, after: ['lintel'], budget: 152000 },

  { key: 'conduit', name: 'Electrical conduiting', stage: 4, days: 8, after: [{ key: 'gfblock', type: 'SS', lag: 5 }], budget: 94000 },
  { key: 'plumbing', name: 'Plumbing rough-in', stage: 4, days: 7, after: [{ key: 'conduit', type: 'SS', lag: 2 }], budget: 112000 },
  { key: 'sump', name: 'Water tank & sump', stage: 4, days: 5, after: ['plinth'], budget: 86000 },
  { key: 'wiring', name: 'Wiring pulling', stage: 4, days: 6, after: ['intplaster', 'conduit'], budget: 78000 },

  { key: 'flooring', name: 'Flooring — tile laying', stage: 5, days: 12, after: ['intplaster'], budget: 286000 },
  { key: 'joinery', name: 'Doors & windows fixing', stage: 5, days: 8, after: ['flooring'], budget: 224000 },
  { key: 'primer', name: 'Painting — putty & primer', stage: 5, days: 6, after: ['joinery', 'extplaster'], budget: 92000 },
  { key: 'paint', name: 'Painting — final coats', stage: 5, days: 8, after: ['primer'], budget: 138000 },
  { key: 'fittings', name: 'Electrical fittings & fixtures', stage: 5, days: 5, after: ['paint', 'wiring'], budget: 104000 },
  { key: 'sanitary', name: 'Sanitary fittings', stage: 5, days: 4, after: ['paint', 'plumbing'], budget: 96000 },
  { key: 'clean', name: 'Final cleaning & snag list', stage: 5, days: 4, after: ['fittings', 'sanitary'], budget: 26000 },
  // Zero days = a milestone. Every programme needs the handover diamond.
  { key: 'handover', name: 'Handover to customer', stage: 5, days: 0, after: ['clean'] },
];

/** Interior renovation - no structure, and everything is tighter. */
const RENOVATION_TEMPLATE: TemplateRow[] = [
  { key: 'strip', name: 'Stripping out old fittings', stage: 1, days: 4, budget: 22000 },
  { key: 'demo', name: 'Breaking old flooring & tiles', stage: 1, days: 5, after: ['strip'], budget: 34000 },
  { key: 'debris', name: 'Debris clearing', stage: 1, days: 2, after: ['demo'], budget: 12000 },

  { key: 'walls', name: 'Wall repairs & new partitions', stage: 2, days: 6, after: ['debris'], budget: 58000 },
  { key: 'waterproof', name: 'Bathroom waterproofing', stage: 2, days: 4, after: ['walls'], budget: 46000 },

  { key: 'replaster', name: 'Re-plastering', stage: 3, days: 8, after: ['walls'], budget: 64000 },

  { key: 'replumb', name: 'Plumbing re-routing', stage: 4, days: 6, after: [{ key: 'walls', type: 'SS', lag: 2 }], budget: 72000 },
  { key: 'rewire', name: 'Electrical re-wiring', stage: 4, days: 5, after: [{ key: 'walls', type: 'SS', lag: 3 }], budget: 54000 },

  { key: 'tiles', name: 'Floor & wall tiling', stage: 5, days: 10, after: ['replaster', 'waterproof'], budget: 148000 },
  { key: 'kitchen', name: 'Kitchen counter & cabinets', stage: 5, days: 9, after: ['tiles'], budget: 186000 },
  { key: 'rvpaint', name: 'Painting', stage: 5, days: 6, after: ['tiles'], budget: 48000 },
  { key: 'rvfittings', name: 'Sanitary & electrical fittings', stage: 5, days: 5, after: ['rvpaint', 'replumb', 'rewire'], budget: 78000 },
  { key: 'rvhandover', name: 'Handover', stage: 5, days: 0, after: ['kitchen', 'rvfittings'] },
];

export interface ScheduleSeedProject {
  id: string;
  start: number;
  /**
   * The project's agreed completion date. Activity durations are scaled so the
   * baseline lands here, which keeps the schedule consistent with the dates
   * already shown on the dashboard and the project list. Without it a template
   * that happens to be shorter than the project's real span finishes in the
   * past, and every activity reads as complete.
   */
  due: number;
  template: 'build' | 'renovation';
  singleStorey?: boolean;
  /**
   * Real-world slippage: this activity actually started N working days after
   * the plan said it would. Everything downstream moves, which is exactly the
   * moment the Schedule tab earns its keep.
   */
  delay?: { key: string; workingDaysLate: number; reason: string };
}

const DAY = 24 * 60 * 60 * 1000;

/**
 * Builds and stores the activities for one project.
 *
 * Runs the schedule twice on purpose: pass one produces the clean plan that is
 * frozen as the baseline, pass two applies the delay so the live dates differ
 * from it. Doing it this way means the "12 days late" on screen was computed,
 * not authored.
 */
export function seedProjectSchedule(p: ScheduleSeedProject): number {
  const rows = (p.template === 'build' ? BUILD_TEMPLATE : RENOVATION_TEMPLATE).filter(
    (r) => !(p.singleStorey && r.upperFloor),
  );

  const idFor = (key: string) => `${p.id}_act_${key}`;
  const present = new Set(rows.map((r) => r.key));

  const raw: ScheduleActivity[] = rows.map((r, i) => ({
    id: idFor(r.key),
    projectId: p.id,
    stageId: `${p.id}_stage_${r.stage}`,
    name: r.name,
    order: i + 1,
    durationDays: r.days,
    percentComplete: 0,
    budgetedCost: r.budget,
    predecessors: (r.after ?? [])
      // A dropped upper-floor row must not leave a dangling link behind it.
      .filter((a) => present.has(typeof a === 'string' ? a : a.key))
      .map((a) =>
        typeof a === 'string'
          ? { predecessorId: idFor(a), type: 'FS' as DependencyType, lagDays: 0 }
          : { predecessorId: idFor(a.key), type: a.type, lagDays: a.lag ?? 0 },
      ),
  }));

  // Stretch or squeeze the template so the plan runs from the project's start
  // to its agreed completion date. The shape of the programme - the sequence,
  // the overlaps, which chain is critical - is unaffected; only the scale is.
  const natural = computeSchedule(raw, { projectStart: p.start }).durationWorkingDays;
  const target = workingDaysBetween(p.start, p.due);
  const factor = natural > 0 && target > 0 ? target / natural : 1;

  const base: ScheduleActivity[] = raw.map((a) => ({
    ...a,
    // Milestones stay at zero; everything else keeps at least a day.
    durationDays: a.durationDays === 0 ? 0 : Math.max(1, Math.round(a.durationDays * factor)),
  }));

  const delayedActivityId = p.delay ? idFor(p.delay.key) : undefined;

  // Pass one: the clean plan. These dates become the baseline.
  const planned = computeSchedule(base, { projectStart: p.start });

  // Pass two: apply the slippage and re-run, giving the dates the job is
  // actually running to.
  const delayed: ScheduleActivity[] = base.map((a) =>
    a.id === delayedActivityId && p.delay
      ? {
          ...a,
          actualStart: planned.byId[a.id].startDate + p.delay.workingDaysLate * DAY,
          delayReason: p.delay.reason,
        }
      : a,
  );
  const current = computeSchedule(delayed, { projectStart: p.start });

  // Pass three: progress is read off the LIVE dates against today, not off the
  // baseline. Using the baseline would mark work complete that the delay has
  // not let anyone start yet - which is exactly the sort of contradiction a
  // builder spots on screen in about two seconds.
  const now = Date.now();

  const live: ScheduleActivity[] = base.map((a) => {
    const plan = planned.byId[a.id];
    const actual = current.byId[a.id];

    const percentComplete = progressAt(now, actual.startDate, actual.finishDate);

    const activity: ScheduleActivity = {
      ...a,
      percentComplete,
      baselineStart: plan.startDate,
      baselineFinish: plan.finishDate,
    };

    // Work that has started carries the date it really began; work that has
    // finished carries both.
    if (percentComplete > 0) activity.actualStart = actual.startDate;
    if (percentComplete >= 100) activity.actualFinish = actual.finishDate;

    if (a.id === delayedActivityId && p.delay) {
      activity.actualStart = actual.startDate;
      activity.actualFinish = undefined;
      activity.delayReason = p.delay.reason;
    }

    return activity;
  });

  live.forEach((a) => {
    store.set(`projects/${p.id}/schedule`, a.id, {
      ...a,
      createdAt: Date.now(),
      updatedAt: Date.now(),
      createdBy: OWNER_UID,
      updatedBy: OWNER_UID,
    });
  });

  // Hand back the duration-weighted completion so the project record can carry
  // the same number. Otherwise the Overview tab quotes one percentage and the
  // Schedule tab beside it quotes another, which is the first thing anyone
  // notices when two tabs are open in front of them.
  const weight = live.reduce((t, a) => t + Math.max(1, a.durationDays), 0);
  const done = live.reduce((t, a) => t + Math.max(1, a.durationDays) * (a.percentComplete / 100), 0);
  return weight > 0 ? Math.round((done / weight) * 100) : 0;
}

/**
 * How far through an activity today is - finished if it is behind us, not
 * started if it is ahead, and proportionally along if we are inside it.
 * Rounded to 5% so the demo reads like someone's estimate rather than a
 * computer's arithmetic.
 */
function progressAt(now: number, start: number, finish: number): number {
  if (now >= finish + DAY) return 100;
  if (now < start) return 0;
  const span = finish + DAY - start;
  if (span <= 0) return 100;
  return Math.min(95, Math.max(5, Math.round(((now - start) / span) * 20) * 5));
}
